import csv,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
OUT=Path(os.environ.get('BROWSER_ARTIFACTS','work/browser-smoke'))
OUT.mkdir(parents=True,exist_ok=True)
BASE_URL=os.environ.get('PREVIEW_URL','http://127.0.0.1:4173').rstrip('/')
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,**({'executable_path':os.environ['CHROME_PATH']} if os.environ.get('CHROME_PATH') else {}))
 results=[]
 for width,height in [(1440,1000),(728,724),(390,844)]:
  page_size=10 if width<600 else 50
  page=browser.new_page(viewport={'width':width,'height':height},device_scale_factor=1)
  errors=[];console=[];failed=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('console',lambda m:console.append(m.text) if m.type=='error' else None)
  page.on('response',lambda r:failed.append({'url':r.url,'status':r.status}) if r.status>=400 else None)
  page.goto(BASE_URL+'/',wait_until='networkidle',timeout=60000)
  expect(page.get_by_role('heading',name='Paper to Power',exact=True)).to_be_visible()
  expect(page.locator('.evidence-table tbody tr')).to_have_count(page_size)
  assert 'have yet to materialize' not in page.locator('body').inner_text()
  assert 'Capacity Gap' not in page.locator('body').inner_text()
  page.wait_for_function('document.querySelector("video").readyState >= 2')
  video=page.locator('video');start=video.evaluate('(v)=>v.currentTime')
  page.wait_for_function('(t)=>document.querySelector("video").currentTime>t',arg=start)
  assert video.evaluate('(v)=>v.muted && !v.paused')
  fonts=page.locator('body,h1,.section-title,.pilot-tabs button').evaluate_all('(els)=>els.map(e=>getComputedStyle(e).fontFamily)')
  assert len(set(fonts))==1,fonts
  page.screenshot(path=str(OUT/f'hero-{width}.png'))
  assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Body overflow'
  expect(page.locator('[data-map-ready="true"]')).to_have_count(2,timeout=30000)
  page.get_by_role('combobox',name='Country',exact=True).select_option('SGP')
  expect(page.locator('.evidence-table tbody tr')).to_have_count(page_size)
  with page.expect_download() as dl:
   page.get_by_role('button',name='Export 104 records (CSV)').click()
  dest=OUT/f'filtered-{width}.csv';dl.value.save_as(str(dest));rows=list(csv.DictReader(dest.open()))
  assert len(rows)==104 and {r['countryCode'] for r in rows}=={'SGP'}
  page.get_by_role('searchbox').fill('Tengeh')
  page.get_by_role('button',name='Sembcorp Tengeh Floating Solar Farm',exact=True).click()
  expect(page.locator('#project-detail-title')).to_have_text('Sembcorp Tengeh Floating Solar Farm')
  drawer=page.locator('.project-drawer')
  assert '60 MWp/DC' in drawer.inner_text()
  assert '2021-07-14' in drawer.inner_text()
  assert drawer.get_by_text('0 MW', exact=True).count() == 0
  assert '0.0' not in drawer.inner_text()
  if width<500:drawer.scroll_into_view_if_needed()
  else:page.locator('.explorer-stage').scroll_into_view_if_needed()
  page.screenshot(path=str(OUT/f'drawer-{width}.png'))
  page.keyboard.press('Escape');expect(page.locator('.project-drawer')).to_have_count(0)
  page.get_by_role('searchbox').fill('')
  page.get_by_text('Review filters',exact=True).click()
  page.get_by_role('combobox',name='Observation status',exact=True).select_option('not_detected_by_cutoff')
  expect(page.get_by_text('No projects match these filters.',exact=True)).to_be_visible()
  page.get_by_role('button',name='Clear filters',exact=True).click();expect(page.locator('.evidence-table tbody tr')).to_have_count(page_size)
  page.get_by_role('combobox',name='Country',exact=True).select_option('PHL')
  page.get_by_role('combobox',name='Technology',exact=True).select_option('wind')
  page.get_by_role('searchbox').fill('Claveria Offshore Wind')
  expect(page.locator('.evidence-table tbody tr')).to_have_count(1)
  page.get_by_role('button',name='Claveria Offshore Wind',exact=True).click()
  assert '2032-04' in page.locator('.project-drawer').inner_text()
  assert 'Method not applicable' in page.locator('.project-drawer').inner_text()
  page.get_by_role('button',name='Close project details',exact=True).click()
  page.get_by_role('button',name='Clear filters',exact=True).click()
  page.get_by_role('searchbox').fill('')
  page.locator('.country-evidence-section').scroll_into_view_if_needed();page.screenshot(path=str(OUT/f'countries-{width}.png'))
  page.get_by_role('button',name='3. Dates and non-detection',exact=False).click()
  assert 'a non-detection percentage is unavailable.' in page.locator('#methodology').inner_text()
  page.locator('#pilot-studies').scroll_into_view_if_needed()
  expect(page.locator('.pilot-tabs').get_by_role('button',name='Tengeh',exact=False)).to_have_attribute('aria-pressed','true')
  expect(page.locator('[data-pilot-map-ready="true"]')).to_have_count(1,timeout=30000)
  asset=page.get_by_role('combobox',name='Mapped asset',exact=True)
  expect(asset.locator('option').filter(has_text='GRW 5 ·')).to_have_count(1)
  selected=asset.locator('option').filter(has_text='GRW 433 ·').get_attribute('value')
  asset.select_option(selected)
  expect(page.locator('.pilot-inspector')).to_contain_text('99.37%')
  slider=page.get_by_role('slider',name='Observation quarter',exact=False)
  slider.focus();slider.press('Home');expect(page.locator('.pilot-time-control')).to_contain_text('0 of 3')
  slider.press('End');expect(page.locator('.pilot-time-control')).to_contain_text('3 of 3')
  page.get_by_role('checkbox',name='Show earlier polygon',exact=True).uncheck()
  expect(asset.locator('option').filter(has_text='GRW 5 ·')).to_have_count(0)
  page.locator('#pilot-studies').screenshot(path=str(OUT/f'pilot-tengeh-{width}.png'))
  page.locator('.pilot-tabs').get_by_role('button',name='Sidrap',exact=False).click()
  expect(page.locator('.pilot-time-control')).to_contain_text('27 of 27')
  expect(page.locator('[data-pilot-map-ready="true"]')).to_have_count(1,timeout=30000)
  page.get_by_text('About this comparison',exact=True).click()
  expect(page.locator('.pilot-note')).to_contain_text('References 19, 24 and 27')
  page.get_by_text('About this comparison',exact=True).click()
  slider=page.get_by_role('slider',name='Observation quarter',exact=False);slider.focus();slider.press('Home');expect(page.locator('.pilot-time-control')).to_contain_text('0 of 27')
  slider.press('End')
  page.locator('#pilot-studies').screenshot(path=str(OUT/f'pilot-sidrap-{width}.png'))
  for path in ['project-evidence.csv','project-evidence.json','release-manifest.json','pilot-attribution-reviews.json','pilot-reference-features.geojson']:
   response=page.request.get(BASE_URL+'/downloads/'+path);assert response.ok,path
  page.screenshot(path=str(OUT/f'methodology-{width}.png'))
  assert not errors,errors
  assert not console,console[:5]
  assert not failed,failed[:5]
  results.append({'viewport':[width,height],'passed':['render','no body overflow','paged records','map workers and sources','country/technology/status filters','empty state','filtered CSV population','drawer sources/dates','Escape close','Claveria offshore date','methodology','download endpoints','pilot switch','quarter slider keyboard','asset review inspector','excluded polygon toggle'],'pageErrors':errors,'consoleErrors':console,'failedResponses':failed})
  page.close()
 browser.close()
 (OUT/'browser-results.json').write_text(json.dumps(results,indent=2)+'\n')
 print(json.dumps(results,indent=2))
