import type { CountryCode, RegistryMapProject } from '../types/domain';
import { countrySummaries } from '../data/generated';
import { SectionHeader } from './shared/SectionHeader';
export function CountrySection({allProjects,onSelectCountry}:{allProjects:readonly RegistryMapProject[];onSelectCountry:(country:CountryCode)=>void}) {
 return <section className="country-evidence-section"><div className="section-container">
  <SectionHeader title="Start with a country" eyebrow="Current coverage" subtitle="Select a country to open its projects in the regional map."/>
  <div className="country-index">{countrySummaries.map(c=><a href="#explorer-section" key={c.code} onClick={()=>onSelectCountry(c.code)} aria-label={`Explore ${c.name} projects`}><span>{c.name}</span><strong>{c.projectCount.toLocaleString()}<span> records</span></strong><span className="country-index-arrow" aria-hidden="true">↗</span></a>)}</div>
  <p className="coverage-scope">The September 2026 regional baseline covers solar, wind, hydropower, geothermal and bioenergy, with pumped storage shown separately. Records describe units and phases; smaller installations remain outside the source’s coverage thresholds.</p>
  <details className="country-coverage-details"><summary>See review coverage by country</summary><div className="country-coverage-scroll"><table><caption>Research coverage for this selection; these counts do not rank national energy performance.</caption><thead><tr><th>Country</th><th>Claims checked</th><th>Mapped coverage</th><th>Reviewed projects with footprints</th><th>Eligible site reviews</th></tr></thead><tbody>{countrySummaries.map(c=><tr key={c.code}><th scope="row">{c.name}</th><td>{c.documentaryReviewedCount} / {c.projectCount}</td><td>{c.hasObservedCoverage?'Available':'Unavailable'}</td><td>{c.approvedFootprintCount}</td><td>{c.eligibleProjectCount}</td></tr>)}</tbody></table></div><p className="evidence-note">Timor-Leste is included. Research supplements are retained separately and may overlap provider records. A non-detection rate is unavailable because no completed site review meets all eligibility requirements. {allProjects.filter(p=>p.capacityBasis==='unspecified').length} records have unresolved capacity bases; AC, DC/peak and hybrid claims remain separate.</p></details>
 </div></section>;
}
